### ISSUE TITLE
Request: would it be possible to port to Apple Silicon 

### ISSUE THREAD

**Issue by dennisdebel** [phkhanhtrinh23/translation_layoutrecovery#7]
Obvious cuda errors when trying to build on M2 Apple Silicon. This is an amazing project and would love to figure out/assist with testing on Macintosh

**Comment by phkhanhtrinh23** [comment]
Hi, can you show us your error? 
During this project, we used OS such as Windows and Linux so we did not face any errors related to the hardware configurations.

**Comment by dennisdebel** [comment]
Hi there, thank you for your reply. The Docker image builds fine but fails to run. This is the final output of the docker compose command:

`Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]`

**Comment by phkhanhtrinh23** [comment]
You can follow this forum: https://forums.developer.nvidia.com/t/could-not-select-device-driver-with-capabilities-gpu/80200

**Comment by dennisdebel** [comment]
It is not possible on Apple Silicon (M1/M2/M3) because there is no discrete GPU that supports CUDA in my understanding. I have found an old machine with an GTX 1070 inside, going to test on that one and if that does not work I will upgrade it to an RTX series GPU. Thank you for replying! Keep you posted
