### ISSUE TITLE
Does this currently support English translation into Chinese?

### ISSUE THREAD

**Issue by liweiyang2023** [phkhanhtrinh23/translation_layoutrecovery#8]
I'm working on this project right now, and I'm a little confused.

**Comment by phkhanhtrinh23** [comment]
For the time being, this repo does not support English translation into Chinese. However, you can set it up by: 
- Use a good pre-trained NMT such as [Helsinki-NLP/opus-mt-zh-en](https://huggingface.co/Helsinki-NLP/opus-mt-zh-en) by replacing the model on this [line](https://github.com/phkhanhtrinh23/translation_layoutrecovery/blob/1c1da6336ff1ba53e07856af8b3b49a57a2e0931/Model/main.py#L202).
- Then choose an appropriate font family for display such as [Source Han Sans CN Light](https://chinesefonts.org/fonts/source-han-sans-cn-light) by replacing the font on this [line](https://github.com/phkhanhtrinh23/translation_layoutrecovery/blob/1c1da6336ff1ba53e07856af8b3b49a57a2e0931/Model/main.py#L173).

The instruction above is just a reference. You can read and follow the code in `main.py` for better usage.

**Comment by dennisdebel** [comment]
I am planning on working on a Chinese to English version, thank you for the pointers @phkhanhtrinh23.
Maybe we can bundle our efforts to add multi language support @liweiyang2023

**Comment by phkhanhtrinh23** [comment]
I guess I provided instruction to setup translation from English to Chinese. I may close this issue. If you guys have any concerns, please re-open it. We extremely appreciate your contribution!
